spring.application.name=freetowear
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect

spring.mvc.hiddenmethod.filter.enabled=true

spring.session.store-type=jdbc
spring.session.jdbc.initialize-schema=always

server.servlet.session.timeout=30m

app.remember-me.key=freetowear-secret-key
app.remember-me.validity-seconds=1209600

spring.mail.host=mx.msgwing.com
spring.mail.port=587
spring.mail.username=${SPRING_MAIL_USERNAME}
spring.mail.password=${SPRING_MAIL_PASSWORD}

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true