package com.freetowear.enums;

public enum OrderEventType {
    ORDER_CREATED,

    PAYMENT_PENDING,
    PAYMENT_APPROVED,
    PAYMENT_REJECTED,
    PAYMENT_PROCESSING,
    PAYMENT_PENDING_REVIEW,
    PAYMENT_REFUNDED,

    WAITING_FOR_STOCK,
    STOCK_REPLENISHMENT,
    STOCK_RESERVED,
    PICKING_STARTED,
    PICKING_COMPLETED,
    ORDER_DISPATCHED,

    COLLECTED,
    IN_TRANSIT,
    AT_DISTRIBUTION_CENTER,
    LEFT_DISTRIBUTION_CENTER,
    OUT_FOR_DELIVERY,

    TRANSPORTATION_DELAY,
    ROUTE_DEVIATION,
    ADDRESS_NOT_FOUND,
    ADDRESS_INCORRECT,
    PACKAGE_DAMAGED,
    PACKAGE_LOST,

    DELIVERY_ATTEMPTED,
    DELIVERY_FAILED,
    AWAITING_PICKUP,
    DELIVERED,

    AWAITING_RETURN,
    IN_RETURN,
    RETURNED,

    COMPLETED,
    CANCELLED
}